/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Pedido;
import java.awt.CardLayout;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.SwingConstants;
import utils.CustomScrollBarUI;

/**
 *
 * @author Eduardo C.
 */
public class ComprasUbeer extends javax.swing.JFrame {
//    private ComprasUbeerController controller;
    private int xMouse;
    private int yMouse;
    public String user;
    public String psw;
    public int userPermission;
    public CardLayout cl;
    public Pedido NovoPedido;
    public DefaultListModel listModel;
    /**
     * Creates new form NewJFrame
     */
    public ComprasUbeer(int userP, String usuario, String senha) {
        this.user=usuario;
        this.psw=senha;
        NovoPedido= new Pedido();
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultListCellRenderer renderer = (DefaultListCellRenderer) listCart.getCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        cl = new CardLayout();
        jPanel1.setLayout(cl);
        listModel = new DefaultListModel();
        listCart.setModel(listModel);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        this.userPermission = userP;
    }
    public ComprasUbeer(int userP) {
        NovoPedido= new Pedido();
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultListCellRenderer renderer = (DefaultListCellRenderer) listCart.getCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        cl = new CardLayout();
        jPanel1.setLayout(cl);
        listModel = new DefaultListModel();
        listCart.setModel(listModel);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        this.userPermission = userP;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrameContainer = new javax.swing.JPanel();
        lblFechar = new javax.swing.JLabel();
        lblUbeerTitle = new javax.swing.JLabel();
        lblUbeerSubtitle = new javax.swing.JLabel();
        pnlLeftMenu = new javax.swing.JPanel();
        btnConfig = new javax.swing.JLabel();
        btnCart = new javax.swing.JLabel();
        lblBannerCarne = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();
        pnlCartContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCart = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnFinalizarPedido = new javax.swing.JButton();
        btnLimparCarrinho = new javax.swing.JButton();
        pnlProdutos = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fielddescprod = new javax.swing.JLabel();
        btnComprarPicanha = new javax.swing.JButton();
        lblprecopicanha = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnComprarMaminha = new javax.swing.JButton();
        lblprecomaminha = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnComprarCarvao = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblprecocarvao = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnComprarCerveja = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblprecocerveja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlFrameContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrameContainer.setLayout(null);

        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_close.png"))); // NOI18N
        lblFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        pnlFrameContainer.add(lblFechar);
        lblFechar.setBounds(1000, 10, 30, 30);

        lblUbeerTitle.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblUbeerTitle.setForeground(new java.awt.Color(76, 19, 1));
        lblUbeerTitle.setText("U-BEER");
        pnlFrameContainer.add(lblUbeerTitle);
        lblUbeerTitle.setBounds(130, 60, 220, 62);

        lblUbeerSubtitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblUbeerSubtitle.setForeground(new java.awt.Color(76, 19, 1));
        lblUbeerSubtitle.setText("SALVANDO SEU CHURRAS !");
        pnlFrameContainer.add(lblUbeerSubtitle);
        lblUbeerSubtitle.setBounds(130, 120, 370, 32);

        pnlLeftMenu.setBackground(new java.awt.Color(77, 19, 1));
        pnlLeftMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_config.png"))); // NOI18N
        btnConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
        });
        pnlLeftMenu.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_cartclicked.png"))); // NOI18N
        btnCart.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLeftMenu.add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pnlFrameContainer.add(pnlLeftMenu);
        pnlLeftMenu.setBounds(0, 0, 70, 670);

        lblBannerCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carnebanner.png"))); // NOI18N
        lblBannerCarne.setText("jLabel18");
        lblBannerCarne.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBannerCarneMouseDragged(evt);
            }
        });
        lblBannerCarne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBannerCarneMousePressed(evt);
            }
        });
        pnlFrameContainer.add(lblBannerCarne);
        lblBannerCarne.setBounds(70, 0, 970, 210);

        pnlContainer.setBackground(new java.awt.Color(196, 110, 83));
        pnlContainer.setLayout(null);

        pnlCartContainer.setBackground(new java.awt.Color(77, 19, 1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setDoubleBuffered(true);

        listCart.setBackground(new java.awt.Color(77, 19, 1));
        listCart.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        listCart.setForeground(new java.awt.Color(255, 255, 255));
        listCart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listCartKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listCart);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CARRINHO");

        btnFinalizarPedido.setText("Fazer Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        btnLimparCarrinho.setText("Limpar Carrinho");
        btnLimparCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCarrinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCartContainerLayout = new javax.swing.GroupLayout(pnlCartContainer);
        pnlCartContainer.setLayout(pnlCartContainerLayout);
        pnlCartContainerLayout.setHorizontalGroup(
            pnlCartContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addGroup(pnlCartContainerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparCarrinho)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(95, 95, 95))
        );
        pnlCartContainerLayout.setVerticalGroup(
            pnlCartContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartContainerLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCartContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizarPedido)
                    .addComponent(btnLimparCarrinho))
                .addGap(18, 18, 18))
        );

        pnlContainer.add(pnlCartContainer);
        pnlCartContainer.setBounds(50, 40, 270, 330);

        pnlProdutos.setBackground(new java.awt.Color(77, 19, 1));
        pnlProdutos.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_previous.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        pnlProdutos.add(jLabel14);
        jLabel14.setBounds(40, 270, 30, 30);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_next.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        pnlProdutos.add(jLabel13);
        jLabel13.setBounds(380, 270, 30, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PRODUTOS");
        pnlProdutos.add(jLabel3);
        jLabel3.setBounds(155, 14, 134, 32);

        jPanel1.setBackground(new java.awt.Color(77, 19, 1));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(77, 19, 1));
        jPanel2.setPreferredSize(new java.awt.Dimension(447, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/picanha.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PICANHA");

        fielddescprod.setForeground(new java.awt.Color(255, 255, 255));
        fielddescprod.setText("<html><p style='text-align:justify;'>Parte mais desejada do churrasco, a Picanha é sucesso no Brasil</p></html>");

        btnComprarPicanha.setText("Comprar");
        btnComprarPicanha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarPicanhaActionPerformed(evt);
            }
        });

        lblprecopicanha.setForeground(new java.awt.Color(255, 255, 255));
        lblprecopicanha.setText("R$: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblprecopicanha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnComprarPicanha)
                    .addComponent(fielddescprod, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblprecopicanha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fielddescprod)
                        .addGap(18, 18, 18)
                        .addComponent(btnComprarPicanha)
                        .addGap(38, 38, 38))))
        );

        jPanel1.add(jPanel2, "card2");

        jPanel3.setBackground(new java.awt.Color(77, 19, 1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/maminha.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MAMINHA");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html><p style='text-align:justify;'>Parte mais macia da alcatra, a Maminha tem um formato quase triangular e é um dos cortes mais populares nas mesas brasileiras.</p></html>");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setIconTextGap(2);

        btnComprarMaminha.setText("Comprar");
        btnComprarMaminha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarMaminhaActionPerformed(evt);
            }
        });

        lblprecomaminha.setForeground(new java.awt.Color(255, 255, 255));
        lblprecomaminha.setText("R$: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblprecomaminha, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnComprarMaminha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblprecomaminha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(btnComprarMaminha))
        );

        jPanel1.add(jPanel3, "card3");

        jPanel4.setBackground(new java.awt.Color(77, 19, 1));

        btnComprarCarvao.setText("Comprar");
        btnComprarCarvao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarCarvaoActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("<html><p style='text-align:justify;'>Carvão 100% Vegetal, o combústivel ideal para o seu churrasco</p></html>");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CARVÃO");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carvao.png"))); // NOI18N

        lblprecocarvao.setForeground(new java.awt.Color(255, 255, 255));
        lblprecocarvao.setText("R$: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComprarCarvao)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(lblprecocarvao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(288, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblprecocarvao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnComprarCarvao)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, "card4");

        jPanel5.setBackground(new java.awt.Color(77, 19, 1));

        btnComprarCerveja.setText("Comprar");
        btnComprarCerveja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarCervejaActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("<html><p style='text-align:justify;'>Bebida alcoólica fermentada a partir de cereais.</p></html>");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cerveja.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CERVEJA");

        lblprecocerveja.setForeground(new java.awt.Color(255, 255, 255));
        lblprecocerveja.setText("R$: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel16)
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(lblprecocerveja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnComprarCerveja)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblprecocerveja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComprarCerveja))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, "card5");

        pnlProdutos.add(jPanel1);
        jPanel1.setBounds(0, 57, 670, 216);

        pnlContainer.add(pnlProdutos);
        pnlProdutos.setBounds(440, 40, 450, 330);

        pnlFrameContainer.add(pnlContainer);
        pnlContainer.setBounds(70, 210, 970, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlFrameContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        
    }//GEN-LAST:event_lblFecharMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void btnComprarPicanhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarPicanhaActionPerformed
        
    }//GEN-LAST:event_btnComprarPicanhaActionPerformed

    private void btnComprarMaminhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarMaminhaActionPerformed
        
    }//GEN-LAST:event_btnComprarMaminhaActionPerformed

    private void btnComprarCarvaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarCarvaoActionPerformed
        
    }//GEN-LAST:event_btnComprarCarvaoActionPerformed

    private void btnComprarCervejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarCervejaActionPerformed
        
    }//GEN-LAST:event_btnComprarCervejaActionPerformed

    private void lblBannerCarneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBannerCarneMousePressed
        this.xMouse = evt.getX();
        this.yMouse = evt.getY();
    }//GEN-LAST:event_lblBannerCarneMousePressed

    private void lblBannerCarneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBannerCarneMouseDragged
        int x = evt.getXOnScreen()-70;
        int y = evt.getYOnScreen();
        this.setLocation(x - this.xMouse, y - this.yMouse);
    }//GEN-LAST:event_lblBannerCarneMouseDragged

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    private void btnLimparCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCarrinhoActionPerformed
        
    }//GEN-LAST:event_btnLimparCarrinhoActionPerformed

    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked
        
    }//GEN-LAST:event_btnConfigMouseClicked

    private void listCartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listCartKeyPressed
                
    }//GEN-LAST:event_listCartKeyPressed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprasUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprasUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprasUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprasUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login tela = new Login();
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnCart;
    public javax.swing.JButton btnComprarCarvao;
    public javax.swing.JButton btnComprarCerveja;
    public javax.swing.JButton btnComprarMaminha;
    public javax.swing.JButton btnComprarPicanha;
    public javax.swing.JLabel btnConfig;
    public javax.swing.JButton btnFinalizarPedido;
    public javax.swing.JButton btnLimparCarrinho;
    public javax.swing.JLabel fielddescprod;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblBannerCarne;
    public javax.swing.JLabel lblFechar;
    public javax.swing.JLabel lblUbeerSubtitle;
    public javax.swing.JLabel lblUbeerTitle;
    public javax.swing.JLabel lblprecocarvao;
    public javax.swing.JLabel lblprecocerveja;
    public javax.swing.JLabel lblprecomaminha;
    public javax.swing.JLabel lblprecopicanha;
    public javax.swing.JList<String> listCart;
    public javax.swing.JPanel pnlCartContainer;
    public javax.swing.JPanel pnlContainer;
    public javax.swing.JPanel pnlFrameContainer;
    public javax.swing.JPanel pnlLeftMenu;
    public javax.swing.JPanel pnlProdutos;
    // End of variables declaration//GEN-END:variables

    
}
