/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DeliverController;
import Model.Pedido;
import Model.Produto;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.SwingConstants;
import utils.CustomScrollBarUI;

/**
 *
 * @author Eduardo C.
 */
public class DeliverUbeer extends javax.swing.JFrame {
//    private ComprasUbeerController controller;
    public ArrayList<Pedido> pedidos = new ArrayList<>();
    private int xMouse;
    private int yMouse;
    public String user;
    public String psw;
    public int userPermission;
    public DefaultListModel listModel;
    public CardLayout cl;
    
    /**
     * Creates new form NewJFrame
     */
    public DeliverUbeer(int userP) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.userPermission = userP;
        listModel = new DefaultListModel();
        listPedido.setModel(listModel);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        
        DefaultListCellRenderer renderer = (DefaultListCellRenderer) listPedido.getCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        
        cl = new CardLayout();
        jPanel1.setLayout(cl);
        pnlProdutos.setVisible(false);
        
        //O PEDIDO ABAIXO É ESTATICO E APENAS PARA TESTE
        
//        Pedido p1 = new Pedido();
//        ArrayList<Produto> produtos = new ArrayList<>();
//        Produto prod1 = new Produto();
//        prod1.setNome("Maminha");
//        prod1.setValor(15);
//        prod1.setQuantidade(3);
//        Produto prod2 = new Produto();
//        prod2.setNome("Picanha");
//        prod2.setValor(11);
//        prod2.setQuantidade(1);
//        produtos.add(prod1);
//        produtos.add(prod2);
//        p1.setProdutos(produtos);
//        p1.setIdcliente(222);
//        p1.setIdpedido(12);
//        pedidos.add(p1);
        
    }
    public DeliverUbeer(int userP, String user,String psw) {
        this.user=user;
        this.psw=psw;
        initComponents();
        this.setLocationRelativeTo(null);
        this.userPermission = userP;
        listModel = new DefaultListModel();
        listPedido.setModel(listModel);
        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());
        
        DefaultListCellRenderer renderer = (DefaultListCellRenderer) listPedido.getCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        
        cl = new CardLayout();
        jPanel1.setLayout(cl);
        pnlProdutos.setVisible(false);
        
        //O PEDIDO ABAIXO É ESTATICO E APENAS PARA TESTE
        
//        Pedido p1 = new Pedido();
//        ArrayList<Produto> produtos = new ArrayList<>();
//        Produto prod1 = new Produto();
//        prod1.setNome("Maminha");
//        prod1.setValor(15);
//        prod1.setQuantidade(3);
//        Produto prod2 = new Produto();
//        prod2.setNome("Picanha");
//        prod2.setValor(11);
//        prod2.setQuantidade(1);
//        produtos.add(prod1);
//        produtos.add(prod2);
//        p1.setProdutos(produtos);
//        p1.setIdcliente(222);
//        p1.setIdpedido(12);
//        pedidos.add(p1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrameContainer = new javax.swing.JPanel();
        lblFechar = new javax.swing.JLabel();
        lblUbeerTitle = new javax.swing.JLabel();
        lblUbeerSubtitle = new javax.swing.JLabel();
        pnlLeftMenu = new javax.swing.JPanel();
        btnConfig = new javax.swing.JLabel();
        btnCart = new javax.swing.JLabel();
        lblBannerCarne = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();
        pnlCartContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPedido = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnEntregar = new javax.swing.JButton();
        lblRefresh = new javax.swing.JLabel();
        btnDetalhes = new javax.swing.JButton();
        pnlProdutos = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblQntPicanha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblQntMaminha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblQntCarvao = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblQntCerveja = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        estadomotoboy = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlFrameContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrameContainer.setLayout(null);

        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_close.png"))); // NOI18N
        lblFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        pnlFrameContainer.add(lblFechar);
        lblFechar.setBounds(1000, 10, 30, 30);

        lblUbeerTitle.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblUbeerTitle.setForeground(new java.awt.Color(76, 19, 1));
        lblUbeerTitle.setText("U-BEER");
        pnlFrameContainer.add(lblUbeerTitle);
        lblUbeerTitle.setBounds(130, 60, 220, 62);

        lblUbeerSubtitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblUbeerSubtitle.setForeground(new java.awt.Color(76, 19, 1));
        lblUbeerSubtitle.setText("SALVANDO SEU CHURRAS !");
        pnlFrameContainer.add(lblUbeerSubtitle);
        lblUbeerSubtitle.setBounds(130, 120, 350, 32);

        pnlLeftMenu.setBackground(new java.awt.Color(77, 19, 1));
        pnlLeftMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_config.png"))); // NOI18N
        btnConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfigMouseClicked(evt);
            }
        });
        pnlLeftMenu.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_clickeddeliver.png"))); // NOI18N
        btnCart.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLeftMenu.add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pnlFrameContainer.add(pnlLeftMenu);
        pnlLeftMenu.setBounds(0, 0, 70, 670);

        lblBannerCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carnebanner.png"))); // NOI18N
        lblBannerCarne.setText("jLabel18");
        lblBannerCarne.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBannerCarneMouseDragged(evt);
            }
        });
        lblBannerCarne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBannerCarneMousePressed(evt);
            }
        });
        pnlFrameContainer.add(lblBannerCarne);
        lblBannerCarne.setBounds(70, 0, 970, 210);

        pnlContainer.setBackground(new java.awt.Color(196, 110, 83));
        pnlContainer.setLayout(null);

        pnlCartContainer.setBackground(new java.awt.Color(77, 19, 1));

        jScrollPane1.setBorder(null);
        jScrollPane1.setDoubleBuffered(true);

        listPedido.setBackground(new java.awt.Color(77, 19, 1));
        listPedido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        listPedido.setForeground(new java.awt.Color(255, 255, 255));
        listPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPedidoMouseClicked(evt);
            }
        });
        listPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listPedidoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listPedido);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PEDIDOS");

        btnEntregar.setText("ENTREGAR");
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        lblRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_refresh.png"))); // NOI18N
        lblRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRefreshMouseClicked(evt);
            }
        });

        btnDetalhes.setText("DETALHES");
        btnDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalhesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCartContainerLayout = new javax.swing.GroupLayout(pnlCartContainer);
        pnlCartContainer.setLayout(pnlCartContainerLayout);
        pnlCartContainerLayout.setHorizontalGroup(
            pnlCartContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
            .addGroup(pnlCartContainerLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRefresh)
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartContainerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnEntregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDetalhes)
                .addGap(21, 21, 21))
        );
        pnlCartContainerLayout.setVerticalGroup(
            pnlCartContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCartContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCartContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lblRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCartContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntregar)
                    .addComponent(btnDetalhes))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlContainer.add(pnlCartContainer);
        pnlCartContainer.setBounds(80, 60, 270, 350);

        pnlProdutos.setBackground(new java.awt.Color(77, 19, 1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_previous.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_next.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DETALHES");

        jPanel1.setBackground(new java.awt.Color(77, 19, 1));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(77, 19, 1));
        jPanel2.setPreferredSize(new java.awt.Dimension(447, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/picanha.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PICANHA");

        lblQntPicanha.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html><p style='text-align:justify;'>Parte mais desejada do churrasco, a Picanha é sucesso no Brasil</p></html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQntPicanha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQntPicanha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );

        jPanel1.add(jPanel2, "card2");

        jPanel3.setBackground(new java.awt.Color(77, 19, 1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/maminha.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MAMINHA");

        lblQntMaminha.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html><p style='text-align:justify;'>Parte mais macia da alcatra, a Maminha tem um formato quase triangular e é um dos cortes mais populares nas mesas brasileiras.</p></html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQntMaminha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQntMaminha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, "card3");

        jPanel4.setBackground(new java.awt.Color(77, 19, 1));

        lblQntCarvao.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CARVÃO");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carvao.png"))); // NOI18N

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html><p style='text-align:justify;'>Carvão 100% Vegetal, o combústivel ideal para o seu churrasco</p></html> ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel12)
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQntCarvao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblQntCarvao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, "card4");

        jPanel5.setBackground(new java.awt.Color(77, 19, 1));

        lblQntCerveja.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cerveja.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CERVEJA");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("<html><p style='text-align:justify;'>Bebida alcoólica fermentada a partir de cereais.</p></html> ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel16)
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(lblQntCerveja, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lblQntCerveja, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, "card5");

        javax.swing.GroupLayout pnlProdutosLayout = new javax.swing.GroupLayout(pnlProdutos);
        pnlProdutos.setLayout(pnlProdutosLayout);
        pnlProdutosLayout.setHorizontalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutosLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel3)
                .addContainerGap(310, Short.MAX_VALUE))
            .addGroup(pnlProdutosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(150, 150, 150))
            .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlProdutosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlProdutosLayout.setVerticalGroup(
            pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addContainerGap())
            .addGroup(pnlProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlProdutosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlContainer.add(pnlProdutos);
        pnlProdutos.setBounds(420, 60, 480, 350);

        estadomotoboy.setBackground(new java.awt.Color(77, 19, 1));
        estadomotoboy.setForeground(new java.awt.Color(255, 255, 255));
        estadomotoboy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Offline", "Online" }));
        estadomotoboy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadomotoboyActionPerformed(evt);
            }
        });
        pnlContainer.add(estadomotoboy);
        estadomotoboy.setBounds(80, 20, 80, 24);

        pnlFrameContainer.add(pnlContainer);
        pnlContainer.setBounds(70, 210, 970, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlFrameContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        
    }//GEN-LAST:event_lblFecharMouseClicked

    private void lblBannerCarneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBannerCarneMousePressed
        this.xMouse = evt.getX();
        this.yMouse = evt.getY();
    }//GEN-LAST:event_lblBannerCarneMousePressed

    private void lblBannerCarneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBannerCarneMouseDragged
        int x = evt.getXOnScreen()-70;
        int y = evt.getYOnScreen();
        this.setLocation(x - this.xMouse, y - this.yMouse);
    }//GEN-LAST:event_lblBannerCarneMouseDragged

    private void btnConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfigMouseClicked
        
    }//GEN-LAST:event_btnConfigMouseClicked

    private void listPedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listPedidoKeyPressed

    }//GEN-LAST:event_listPedidoKeyPressed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
        
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        
    }//GEN-LAST:event_jLabel13MouseClicked

    private void lblRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRefreshMouseClicked
        
    }//GEN-LAST:event_lblRefreshMouseClicked

    private void listPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPedidoMouseClicked
        
    }//GEN-LAST:event_listPedidoMouseClicked

    private void btnDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhesActionPerformed
        
    }//GEN-LAST:event_btnDetalhesActionPerformed

    private void estadomotoboyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadomotoboyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadomotoboyActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliverUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliverUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliverUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliverUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                Login tela = new Login();
//                tela.setLocationRelativeTo(null);
//                tela.setVisible(true);
                DeliverUbeer tela = new DeliverUbeer(0);
                tela.setVisible(true);
                DeliverController c = new DeliverController(tela);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnCart;
    public javax.swing.JLabel btnConfig;
    public javax.swing.JButton btnDetalhes;
    public javax.swing.JButton btnEntregar;
    public javax.swing.JComboBox<String> estadomotoboy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblBannerCarne;
    public javax.swing.JLabel lblFechar;
    public javax.swing.JLabel lblQntCarvao;
    public javax.swing.JLabel lblQntCerveja;
    public javax.swing.JLabel lblQntMaminha;
    public javax.swing.JLabel lblQntPicanha;
    public javax.swing.JLabel lblRefresh;
    public javax.swing.JLabel lblUbeerSubtitle;
    public javax.swing.JLabel lblUbeerTitle;
    public javax.swing.JList<String> listPedido;
    public javax.swing.JPanel pnlCartContainer;
    public javax.swing.JPanel pnlContainer;
    public javax.swing.JPanel pnlFrameContainer;
    public javax.swing.JPanel pnlLeftMenu;
    public javax.swing.JPanel pnlProdutos;
    // End of variables declaration//GEN-END:variables

    
}
