/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.CardLayout;


/**
 *
 * @author Edu
 */
public class Login extends javax.swing.JFrame {
    public CardLayout clBtn;
    public CardLayout clSign;
    public int userPermission;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setSize(300, 400);
        setLocationRelativeTo(null);
        lblDescApp.setText("<HTML><p style='text-align:center;'>Por favor nos informe como quer prosseguir :)");
        btnMotoboy.setFocusPainted(false);
        btnCliente.setFocusPainted(false);
        clBtn = new CardLayout();
        clSign = new CardLayout();
        pnlSign.setLayout(clSign);
        pnlBtnSlider.setLayout(clBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlLoginComponents = new javax.swing.JPanel();
        pnlSign = new javax.swing.JPanel();
        pnlSignInfo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fieldlogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldpsw = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        pnlSignInfo1 = new javax.swing.JPanel();
        fieldcadastroemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldcadbairro = new javax.swing.JTextField();
        btnRegistrarConta = new javax.swing.JButton();
        fieldcadastrologin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldcadastropsw = new javax.swing.JTextField();
        fieldcadcpf = new javax.swing.JTextField();
        pnlInit = new javax.swing.JPanel();
        pnlBtnSlider = new javax.swing.JPanel();
        pnlBotoesLogin = new javax.swing.JPanel();
        btnMotoboy = new javax.swing.JButton();
        btnCliente = new javax.swing.JButton();
        pnlBotoesRegistrar = new javax.swing.JPanel();
        btnSliderLogin = new javax.swing.JButton();
        btnSliderVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblDescApp = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFechar = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlContainer.setLayout(null);

        pnlLoginComponents.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginComponents.setLayout(null);

        pnlSign.setLayout(new java.awt.CardLayout());

        pnlSignInfo.setBackground(new java.awt.Color(255, 255, 255));
        pnlSignInfo.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(77, 19, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlSignInfo.add(jPanel1);
        jPanel1.setBounds(0, 90, 210, 1);

        jPanel2.setBackground(new java.awt.Color(77, 19, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        pnlSignInfo.add(jPanel2);
        jPanel2.setBounds(0, 180, 210, 1);

        fieldlogin.setBackground(new java.awt.Color(255, 255, 255));
        fieldlogin.setForeground(new java.awt.Color(77, 19, 1));
        fieldlogin.setBorder(null);
        pnlSignInfo.add(fieldlogin);
        fieldlogin.setBounds(0, 60, 190, 30);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 19, 1));
        jLabel1.setText("USÚARIO");
        pnlSignInfo.add(jLabel1);
        jLabel1.setBounds(0, 40, 90, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(77, 19, 1));
        jLabel3.setText("SENHA");
        pnlSignInfo.add(jLabel3);
        jLabel3.setBounds(0, 130, 70, 24);

        fieldpsw.setBackground(new java.awt.Color(255, 255, 255));
        fieldpsw.setForeground(new java.awt.Color(77, 19, 1));
        fieldpsw.setBorder(null);
        pnlSignInfo.add(fieldpsw);
        fieldpsw.setBounds(0, 150, 190, 30);

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlSignInfo.add(btnLogin);
        btnLogin.setBounds(0, 230, 80, 25);

        pnlSign.add(pnlSignInfo, "card2");

        pnlSignInfo1.setBackground(new java.awt.Color(255, 255, 255));
        pnlSignInfo1.setLayout(null);

        fieldcadastroemail.setBackground(new java.awt.Color(255, 255, 255));
        fieldcadastroemail.setForeground(new java.awt.Color(77, 19, 1));
        fieldcadastroemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlSignInfo1.add(fieldcadastroemail);
        fieldcadastroemail.setBounds(0, 70, 190, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(77, 19, 1));
        jLabel5.setText("E-MAIL");
        pnlSignInfo1.add(jLabel5);
        jLabel5.setBounds(0, 50, 60, 20);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(77, 19, 1));
        jLabel6.setText("ENDEREÇO");
        pnlSignInfo1.add(jLabel6);
        jLabel6.setBounds(0, 170, 120, 24);

        fieldcadbairro.setBackground(new java.awt.Color(255, 255, 255));
        fieldcadbairro.setForeground(new java.awt.Color(77, 19, 1));
        fieldcadbairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlSignInfo1.add(fieldcadbairro);
        fieldcadbairro.setBounds(0, 200, 190, 20);

        btnRegistrarConta.setText("REGISTRAR");
        btnRegistrarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarContaActionPerformed(evt);
            }
        });
        pnlSignInfo1.add(btnRegistrarConta);
        btnRegistrarConta.setBounds(80, 240, 110, 25);

        fieldcadastrologin.setBackground(new java.awt.Color(255, 255, 255));
        fieldcadastrologin.setForeground(new java.awt.Color(77, 19, 1));
        fieldcadastrologin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlSignInfo1.add(fieldcadastrologin);
        fieldcadastrologin.setBounds(0, 30, 190, 20);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(77, 19, 1));
        jLabel7.setText("USÚARIO");
        pnlSignInfo1.add(jLabel7);
        jLabel7.setBounds(0, 10, 80, 20);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(77, 19, 1));
        jLabel8.setText("SENHA");
        pnlSignInfo1.add(jLabel8);
        jLabel8.setBounds(0, 90, 70, 24);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(77, 19, 1));
        jLabel9.setText("CNH/CPF");
        pnlSignInfo1.add(jLabel9);
        jLabel9.setBounds(0, 130, 90, 24);

        fieldcadastropsw.setBackground(new java.awt.Color(255, 255, 255));
        fieldcadastropsw.setForeground(new java.awt.Color(77, 19, 1));
        fieldcadastropsw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlSignInfo1.add(fieldcadastropsw);
        fieldcadastropsw.setBounds(0, 110, 190, 20);

        fieldcadcpf.setBackground(new java.awt.Color(255, 255, 255));
        fieldcadcpf.setForeground(new java.awt.Color(77, 19, 1));
        fieldcadcpf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldcadcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldcadcpfActionPerformed(evt);
            }
        });
        pnlSignInfo1.add(fieldcadcpf);
        fieldcadcpf.setBounds(0, 150, 190, 20);

        pnlSign.add(pnlSignInfo1, "pnl2");

        pnlLoginComponents.add(pnlSign);
        pnlSign.setBounds(390, 70, 240, 270);

        pnlInit.setBackground(new java.awt.Color(77, 19, 1));
        pnlInit.setLayout(null);

        pnlBtnSlider.setOpaque(false);
        pnlBtnSlider.setLayout(new java.awt.CardLayout());

        pnlBotoesLogin.setOpaque(false);

        btnMotoboy.setBackground(new java.awt.Color(255, 255, 255));
        btnMotoboy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMotoboy.setForeground(new java.awt.Color(196, 110, 83));
        btnMotoboy.setText("MOTOBOY");
        btnMotoboy.setBorder(null);
        btnMotoboy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMotoboyActionPerformed(evt);
            }
        });

        btnCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(196, 110, 83));
        btnCliente.setText("CLIENTE");
        btnCliente.setBorder(null);
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLoginLayout = new javax.swing.GroupLayout(pnlBotoesLogin);
        pnlBotoesLogin.setLayout(pnlBotoesLoginLayout);
        pnlBotoesLoginLayout.setHorizontalGroup(
            pnlBotoesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLoginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlBotoesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMotoboy, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlBotoesLoginLayout.setVerticalGroup(
            pnlBotoesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLoginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMotoboy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlBtnSlider.add(pnlBotoesLogin, "card2");

        pnlBotoesRegistrar.setOpaque(false);

        btnSliderLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnSliderLogin.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSliderLogin.setForeground(new java.awt.Color(196, 110, 83));
        btnSliderLogin.setText("REGISTRAR");
        btnSliderLogin.setBorder(null);
        btnSliderLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSliderLoginActionPerformed(evt);
            }
        });

        btnSliderVoltar.setBackground(new java.awt.Color(255, 255, 255));
        btnSliderVoltar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSliderVoltar.setForeground(new java.awt.Color(196, 110, 83));
        btnSliderVoltar.setText("VOLTAR");
        btnSliderVoltar.setBorder(null);
        btnSliderVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSliderVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesRegistrarLayout = new javax.swing.GroupLayout(pnlBotoesRegistrar);
        pnlBotoesRegistrar.setLayout(pnlBotoesRegistrarLayout);
        pnlBotoesRegistrarLayout.setHorizontalGroup(
            pnlBotoesRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesRegistrarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlBotoesRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSliderVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSliderLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlBotoesRegistrarLayout.setVerticalGroup(
            pnlBotoesRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesRegistrarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnSliderLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSliderVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pnlBtnSlider.add(pnlBotoesRegistrar, "card3");

        pnlInit.add(pnlBtnSlider);
        pnlBtnSlider.setBounds(50, 210, 210, 130);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("OI AMIGO!");
        pnlInit.add(jLabel4);
        jLabel4.setBounds(60, 80, 200, 80);

        lblDescApp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblDescApp.setForeground(new java.awt.Color(255, 255, 255));
        lblDescApp.setText("Carregando...");
        pnlInit.add(lblDescApp);
        lblDescApp.setBounds(70, 130, 160, 70);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logoubeerkaka.png"))); // NOI18N
        jLabel2.setText("LOGO");
        pnlInit.add(jLabel2);
        jLabel2.setBounds(0, 0, 70, 60);

        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_close.png"))); // NOI18N
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        pnlInit.add(lblFechar);
        lblFechar.setBounds(270, 0, 30, 30);

        lblBG.setForeground(new java.awt.Color(196, 110, 83));
        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_bglogin.jpg"))); // NOI18N
        pnlInit.add(lblBG);
        lblBG.setBounds(0, 0, 300, 490);

        pnlLoginComponents.add(pnlInit);
        pnlInit.setBounds(0, 0, 300, 400);

        pnlContainer.add(pnlLoginComponents);
        pnlLoginComponents.setBounds(0, 0, 700, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnMotoboyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMotoboyActionPerformed
        
    }//GEN-LAST:event_btnMotoboyActionPerformed

    private void btnSliderLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSliderLoginActionPerformed
        
    }//GEN-LAST:event_btnSliderLoginActionPerformed

    private void btnSliderVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSliderVoltarActionPerformed
        
    }//GEN-LAST:event_btnSliderVoltarActionPerformed

    private void btnRegistrarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarContaActionPerformed
        
    }//GEN-LAST:event_btnRegistrarContaActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        
    }//GEN-LAST:event_lblFecharMouseClicked

    private void fieldcadcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldcadcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldcadcpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login l = new Login();
                l.setVisible(true);
                l.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCliente;
    public javax.swing.JButton btnLogin;
    public javax.swing.JButton btnMotoboy;
    public javax.swing.JButton btnRegistrarConta;
    public javax.swing.JButton btnSliderLogin;
    public javax.swing.JButton btnSliderVoltar;
    public javax.swing.JTextField fieldcadastroemail;
    public javax.swing.JTextField fieldcadastrologin;
    public javax.swing.JTextField fieldcadastropsw;
    public javax.swing.JTextField fieldcadbairro;
    public javax.swing.JTextField fieldcadcpf;
    public javax.swing.JTextField fieldlogin;
    public javax.swing.JTextField fieldpsw;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblBG;
    public javax.swing.JLabel lblDescApp;
    public javax.swing.JLabel lblFechar;
    public javax.swing.JPanel pnlBotoesLogin;
    public javax.swing.JPanel pnlBotoesRegistrar;
    public javax.swing.JPanel pnlBtnSlider;
    public javax.swing.JPanel pnlContainer;
    public javax.swing.JPanel pnlInit;
    public javax.swing.JPanel pnlLoginComponents;
    public javax.swing.JPanel pnlSign;
    public javax.swing.JPanel pnlSignInfo;
    public javax.swing.JPanel pnlSignInfo1;
    // End of variables declaration//GEN-END:variables

    
}
