/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


/**
 *
 * @author Eduardo C.
 */
public class MotoboyConfigUbeer extends javax.swing.JFrame {
//    private ComprasUbeerController controller;
    private int xMouse;
    private int yMouse;
    public int userPermission;
    public String user;
    public String psw;
    /**
     * Creates new form NewJFrame
     */
    public MotoboyConfigUbeer(int userP, String user, String psw) {
        this.user=user;
        this.psw=psw;
        initComponents();
        this.setLocationRelativeTo(null);
        this.userPermission = userP;
    }
    
    
    public MotoboyConfigUbeer(int userP) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.userPermission = userP;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFrameContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUbeerTitle = new javax.swing.JLabel();
        lblUbeerSubtitle = new javax.swing.JLabel();
        pnlLeftMenu = new javax.swing.JPanel();
        btnConfig = new javax.swing.JLabel();
        btnCart = new javax.swing.JLabel();
        lblBannerCarne = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblattemail = new javax.swing.JTextField();
        lblattsenha = new javax.swing.JTextField();
        btnattcad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlFrameContainer.setBackground(new java.awt.Color(255, 255, 255));
        pnlFrameContainer.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_close.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pnlFrameContainer.add(jLabel1);
        jLabel1.setBounds(1000, 10, 30, 30);

        lblUbeerTitle.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lblUbeerTitle.setForeground(new java.awt.Color(76, 19, 1));
        lblUbeerTitle.setText("U-BEER");
        pnlFrameContainer.add(lblUbeerTitle);
        lblUbeerTitle.setBounds(130, 60, 220, 62);

        lblUbeerSubtitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblUbeerSubtitle.setForeground(new java.awt.Color(76, 19, 1));
        lblUbeerSubtitle.setText("SALVANDO SEU CHURRAS !");
        pnlFrameContainer.add(lblUbeerSubtitle);
        lblUbeerSubtitle.setBounds(130, 120, 340, 32);

        pnlLeftMenu.setBackground(new java.awt.Color(77, 19, 1));
        pnlLeftMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_clickedconfig.png"))); // NOI18N
        btnConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlLeftMenu.add(btnConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_deliver.png"))); // NOI18N
        btnCart.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCartMouseClicked(evt);
            }
        });
        pnlLeftMenu.add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        pnlFrameContainer.add(pnlLeftMenu);
        pnlLeftMenu.setBounds(0, 0, 70, 670);

        lblBannerCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/carnebanner.png"))); // NOI18N
        lblBannerCarne.setText("jLabel18");
        lblBannerCarne.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBannerCarneMouseDragged(evt);
            }
        });
        lblBannerCarne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBannerCarneMousePressed(evt);
            }
        });
        pnlFrameContainer.add(lblBannerCarne);
        lblBannerCarne.setBounds(70, 0, 970, 210);

        pnlContainer.setBackground(new java.awt.Color(196, 110, 83));
        pnlContainer.setLayout(null);

        pnlHome.setBackground(new java.awt.Color(196, 110, 83));
        pnlHome.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(77, 19, 1));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ATUALIZAR DADOS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 0, 172, 53);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMAIL:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 140, 90, 19);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SENHA:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 80, 70, 19);

        lblattemail.setBackground(new java.awt.Color(77, 19, 1));
        lblattemail.setForeground(new java.awt.Color(255, 255, 255));
        lblattemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblattemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblattemailActionPerformed(evt);
            }
        });
        jPanel1.add(lblattemail);
        lblattemail.setBounds(140, 160, 260, 30);

        lblattsenha.setBackground(new java.awt.Color(77, 19, 1));
        lblattsenha.setForeground(new java.awt.Color(255, 255, 255));
        lblattsenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        lblattsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblattsenhaActionPerformed(evt);
            }
        });
        jPanel1.add(lblattsenha);
        lblattsenha.setBounds(140, 100, 260, 30);

        btnattcad.setForeground(new java.awt.Color(255, 255, 255));
        btnattcad.setText("ATUALIZAR");
        jPanel1.add(btnattcad);
        btnattcad.setBounds(300, 260, 100, 25);

        pnlHome.add(jPanel1);
        jPanel1.setBounds(200, 60, 540, 367);

        pnlContainer.add(pnlHome);
        pnlHome.setBounds(0, 0, 970, 460);

        pnlFrameContainer.add(pnlContainer);
        pnlContainer.setBounds(70, 210, 970, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFrameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlFrameContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void lblBannerCarneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBannerCarneMousePressed
        this.xMouse = evt.getX();
        this.yMouse = evt.getY();
    }//GEN-LAST:event_lblBannerCarneMousePressed

    private void lblBannerCarneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBannerCarneMouseDragged
        int x = evt.getXOnScreen()-70;
        int y = evt.getYOnScreen();
        this.setLocation(x - this.xMouse, y - this.yMouse);
    }//GEN-LAST:event_lblBannerCarneMouseDragged

    private void btnCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCartMouseClicked
        
    }//GEN-LAST:event_btnCartMouseClicked

    private void lblattemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblattemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblattemailActionPerformed

    private void lblattsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblattsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblattsenhaActionPerformed
    

    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotoboyConfigUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotoboyConfigUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotoboyConfigUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotoboyConfigUbeer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login tela = new Login();
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel btnCart;
    public javax.swing.JLabel btnConfig;
    public javax.swing.JButton btnattcad;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblBannerCarne;
    public javax.swing.JLabel lblUbeerSubtitle;
    public javax.swing.JLabel lblUbeerTitle;
    public javax.swing.JTextField lblattemail;
    public javax.swing.JTextField lblattsenha;
    public javax.swing.JPanel pnlContainer;
    public javax.swing.JPanel pnlFrameContainer;
    public javax.swing.JPanel pnlHome;
    public javax.swing.JPanel pnlLeftMenu;
    // End of variables declaration//GEN-END:variables
}
